<?xml version="1.0"?>
<!-- CORBA XML document created by XMLSerializer2 1.6 at 2022-04-08 11:47:02 UTC, from SL 2.81-r39274 built 2013-12-15 02:02:53 UTC -->
<!DOCTYPE any [
<!ELEMENT any (any|typecode|sequence|array|struct|union|exception|string|objectref|enum|boolean|char|octet|short|ushort|long|ulong|float|double)?>
<!ATTLIST any name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED version CDATA #IMPLIED>
<!ELEMENT typecode (any|typecode|sequence|array|struct|union|exception|string|objectref|enum|boolean|char|octet|short|ushort|long|ulong|float|double)?>
<!ATTLIST typecode name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT sequence ((any|typecode|sequence|array|struct|union|exception|string|objectref)+|(enum|boolean|char|octet|short|ushort|long|ulong|float|double))?>
<!ATTLIST sequence name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED length NMTOKEN #REQUIRED bound NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT array ((any|typecode|sequence|array|struct|union|exception|string|objectref)+|(enum|boolean|char|octet|short|ushort|long|ulong|float|double))?>
<!ATTLIST array name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED length NMTOKEN #REQUIRED label NMTOKEN #IMPLIED>
<!ELEMENT struct (any|typecode|sequence|array|struct|union|exception|string|objectref|enum|boolean|char|octet|short|ushort|long|ulong|float|double)*>
<!ATTLIST struct name NMTOKEN #IMPLIED type_id CDATA #REQUIRED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT union (any|typecode|sequence|array|struct|union|exception|string|objectref|enum|boolean|char|octet|short|ushort|long|ulong|float|double)*>
<!ATTLIST union name NMTOKEN #IMPLIED type_id CDATA #REQUIRED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT exception (any|typecode|sequence|array|struct|union|exception|string|objectref|enum|boolean|char|octet|short|ushort|long|ulong|float|double)*>
<!ATTLIST exception name NMTOKEN #IMPLIED type_id CDATA #REQUIRED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT string (#PCDATA)>
<!ATTLIST string name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED bound NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT objectref (#PCDATA)>
<!ATTLIST objectref name NMTOKEN #IMPLIED type_id CDATA #REQUIRED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT enum (#PCDATA)>
<!ATTLIST enum name NMTOKEN #IMPLIED type_id CDATA #REQUIRED type_name NMTOKEN #IMPLIED values NMTOKENS #REQUIRED label NMTOKEN #IMPLIED>
<!ELEMENT boolean (#PCDATA)>
<!ATTLIST boolean name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT char (#PCDATA)>
<!ATTLIST char name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT octet (#PCDATA)>
<!ATTLIST octet name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT short (#PCDATA)>
<!ATTLIST short name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT ushort (#PCDATA)>
<!ATTLIST ushort name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT long (#PCDATA)>
<!ATTLIST long name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT ulong (#PCDATA)>
<!ATTLIST ulong name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT float (#PCDATA)>
<!ATTLIST float name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
<!ELEMENT double (#PCDATA)>
<!ATTLIST double name NMTOKEN #IMPLIED type_id CDATA #IMPLIED type_name NMTOKEN #IMPLIED label NMTOKEN #IMPLIED>
]>
<any version="1.6">
<sequence length="4" type_id="IDL:specs.de/Serializer/RegionGroupSeq:1.0" type_name="RegionGroupSeq">
<struct type_id="IDL:specs.de/Serializer/RegionGroup:1.0" type_name="RegionGroup">
<string name="name">PBTTT 1.2 V</string>
<sequence name="regions" length="4" type_id="IDL:specs.de/Serializer/RegionDataSeq:1.0" type_name="RegionDataSeq">
<struct type_id="IDL:specs.de/Serializer/RegionData:1.0" type_name="RegionData">
<string name="name">Survey</string>
<struct name="region" type_id="IDL:specs.de/SurfaceAnalysis/RegionDef:1.0" type_name="RegionDef">
<string name="analysis_method">XPS</string>
<string name="analyzer_lens">MediumMagnification:1.5kV</string>
<string name="detector_dataset">XPS_MedMag</string>
<string name="detector_dataset_directory">C:\Program Files (x86)\SPECS\SpecsLab2\database\datasetCalib1d\2021_06</string>
<string name="analyzer_slit">1:0.2x20c\1:open</string>
<struct name="scan_mode" type_id="IDL:specs.de/SurfaceAnalysis/ScanMode:1.0" type_name="ScanMode">
<string name="name">FixedAnalyzerTransmission</string>
<ulong name="flags" type_id="IDL:specs.de/SurfaceAnalysis/ScanModeFlags:1.0" type_name="ScanModeFlags">2</ulong>
</struct>
<ulong name="num_scans">1</ulong>
<ulong name="curves_per_scan">1</ulong>
<ulong name="values_per_curve">1403</ulong>
<double name="dwell_time">0.1</double>
<double name="scan_delta">0.5</double>
<double name="excitation_energy">1253.6</double>
<double name="kinetic_energy">553.6</double>
<double name="kinetic_energy_base">0</double>
<double name="pass_energy">50</double>
<double name="bias_voltage">90</double>
<double name="detector_voltage">2400</double>
<double name="effective_workfunction">4.37</double>
</struct>
<ulong name="mcd_head">8</ulong>
<ulong name="mcd_tail">7</ulong>
<struct name="analyzer_info" type_id="IDL:specs.de/SurfaceAnalysis/AnalyzerInfo:1.0" type_name="AnalyzerInfo">
<string name="name">PHOIBOS HSA3500 100 R6-HORN[HWType 30:7] MCD-5</string>
<sequence name="detectors" length="5" type_id="IDL:specs.de/SurfaceAnalysis/DetectorSeq:1.0" type_name="DetectorSeq">
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-16</double>
<double name="shift">-0.0744451</double>
<double name="gain">1</double>
<sequence name="parameters" length="2" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq">
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Threshold [mV]</string>
<any name="value">
<double>2.87109375</double>
</any>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Deadtime [ns]</string>
<any name="value">
<double>-0</double>
</any>
</struct>
</sequence>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">-8</double>
<double name="shift">-0.0348058</double>
<double name="gain">1</double>
<sequence name="parameters" length="2" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq">
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Threshold [mV]</string>
<any name="value">
<double>2.87109375</double>
</any>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Deadtime [ns]</string>
<any name="value">
<double>-0</double>
</any>
</struct>
</sequence>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">0</double>
<double name="shift">0.00538331</double>
<double name="gain">1</double>
<sequence name="parameters" length="2" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq">
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Threshold [mV]</string>
<any name="value">
<double>2.87109375</double>
</any>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Deadtime [ns]</string>
<any name="value">
<double>-0</double>
</any>
</struct>
</sequence>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">8</double>
<double name="shift">0.0444291</double>
<double name="gain">1</double>
<sequence name="parameters" length="2" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq">
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Threshold [mV]</string>
<any name="value">
<double>2.87109375</double>
</any>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Deadtime [ns]</string>
<any name="value">
<double>-0</double>
</any>
</struct>
</sequence>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Detector:1.0" type_name="Detector">
<double name="position">16</double>
<double name="shift">0.0824935</double>
<double name="gain">1</double>
<sequence name="parameters" length="2" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq">
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Threshold [mV]</string>
<any name="value">
<double>2.87109375</double>
</any>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Deadtime [ns]</string>
<any name="value">
<double>-0</double>
</any>
</struct>
</sequence>
</struct>
</sequence>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
</struct>
<struct name="source_info" type_id="IDL:specs.de/SurfaceAnalysis/SourceInfo:1.0" type_name="SourceInfo">
<string name="name">XRayDummy</string>
<sequence name="excitations" length="1" type_id="IDL:specs.de/SurfaceAnalysis/ExcitationSeq:1.0" type_name="ExcitationSeq">
<struct type_id="IDL:specs.de/SurfaceAnalysis/Excitation:1.0" type_name="Excitation">
<double name="energy">1253.6</double>
<double name="lorentz_width">0.7</double>
<double name="gauss_width">0</double>
<double name="intensity">1</double>
</struct>
</sequence>
<sequence name="parameters" length="5" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq">
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Anode</string>
<any name="value">
<enum values="Mg Al Ag AlMono AgMono Y_M_zeta Zr_M_zeta Nb_M_zeta Mo_M_zeta Ti_L_alpha Cr_L_alpha Ni_L_alpha Cu_L_alpha Mg_K_alpha Al_K_alpha Si_K_alpha Y_L_alpha Zr_L_alpha Au_M_alpha Mo_L_alpha Ag_L_alpha Ti_K_alpha Cr_K_alpha Cu_K_alpha AlMicro1 AlMicro2 AlMicro3 AlMicro4 UserDefined" type_id="IDL:specs.de/XRayAnode/Anode:1.0" type_name="Anode">Mg</enum>
</any>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Power [W]</string>
<any name="value">
<double>0</double>
</any>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Voltage [kV]</string>
<any name="value">
<double>0</double>
</any>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">Angle [deg]</string>
<any name="value">
<double>45</double>
</any>
</struct>
<struct type_id="IDL:specs.de/SurfaceAnalysis/Parameter:1.0" type_name="Parameter">
<string name="name">End of acquisition</string>
<any name="value">
<enum values="Off Standby Operate" type_id="IDL:specs.de/SurfaceAnalysis/SourceState:1.0" type_name="SourceState">Off</enum>
</any>
</struct>
</sequence>
<boolean name="intensity_scaling">0</boolean>
</struct>
<struct name="remote_info" type_id="IDL:specs.de/SurfaceAnalysis/RemoteInfo:1.0" type_name="RemoteInfo">
<string name="name"/>
<enum name="frequency" values="Never PerRegion PerScan PerValue AfterRegion AfterScan AfterValue PerValueAndScan" type_id="IDL:specs.de/SurfaceAnalysis/RemoteFrequency:1.0" type_name="RemoteFrequency">Never</enum>
<sequence name="parameters" length="0" type_id="IDL:specs.de/SurfaceAnalysis/ParameterSeq:1.0" type_name="ParameterSeq"/>
<sequence name="channel_names" length="0" type_id="IDL:specs.de/SurfaceAnalysis/StringSeq:1.0" type_name="StringSeq"/>
<sequence name="channel_units" length="0" type_id="IDL:specs.de/SurfaceAnalysis/StringSeq:1.0" type_name="StringSeq"/>
</struct>
<sequence name="cycles" length="1" type_id="IDL:specs.de/Serializer/CycleSeq:1.0" type_name="CycleSeq">
<struct type_id="IDL:specs.de/Serializer/Cycle:1.0" type_name="Cycle">
<ulong name="time">1643391325</ulong>
<sequence name="scans" length="1" type_id="IDL:specs.de/Serializer/ScanSeq:1.0" type_name="ScanSeq">
<struct type_id="IDL:specs.de/Serializer/ScanData:1.0" type_name="ScanData">
<sequence name="counts" length="7090" type_id="IDL:specs.de/SurfaceAnalysis/CountsSeq:1.0" type_name="CountsSeq">
<ulong type_id="IDL:specs.de/SurfaceAnalysis/Counts:1.0" type_name="Counts">
89
70
91
98
124
62
69
78
99
123
69
67
79
104
84
69
80
97
126
121
79
71
93
113
110
69
70
94
118
93
65
68
86
91
97
56
77
94
131
123
72
71
101
109
119
63
65
77
88
104
62
63
89
109
118
80
63
76
100
105
76
69
90
92
108
54
76
75
83
119
62
65
77
101
99
77
82
82
114
116
63
75
71
104
103
52
63
79
102
122
73
67
83
96
97
62
78
77
106
150
53
75
90
117
120
58
88
84
127
137
56
67
80
130
194
64
45
88
136
224
50
80
75
139
250
52
67
88
165
261
48
88
89
173
234
62
69
83
173
175
54
58
102
244
146
54
64
125
230
124
44
67
143
202
126
52
57
167
189
114
63
87
180
138
96
57
87
175
114
104
58
123
138
119
103
53
126
116
100
95
60
149
101
100
109
80
139
78
101
118
79
137
67
103
99
127
95
95
106
99
128
78
71
80
126
133
78
75
98
91
117
71
81
105
128
97
73
85
100
116
70
71
80
110
119
65
71
86
110
114
58
56
84
124
135
54
56
81
102
100
63
51
79
136
117
49
73
94
93
119
56
87
90
95
113
49
70
70
101
127
62
68
96
103
108
61
72
92
106
100
62
71
74
86
87
71
73
63
92
102
56
69
90
89
89
58
71
70
103
110
74
70
89
94
103
75
56
80
101
118
58
58
75
104
111
53
55
75
96
102
53
61
77
99
112
56
58
89
108
101
59
66
72
114
104
46
62
84
94
102
73
66
71
105
113
47
62
78
111
111
64
65
82
98
89
57
77
87
104
103
70
69
72
93
95
51
65
77
85
90
50
61
68
93
104
62
60
72
99
107
57
68
79
92
114
50
72
61
102
116
64
65
70
85
98
67
63
79
90
100
49
67
68
113
81
52
67
74
107
112
52
67
62
109
120
49
75
84
99
104
61
69
73
102
106
61
70
80
99
111
47
76
87
92
95
39
66
80
97
119
52
61
79
117
110
53
61
84
85
97
62
58
78
90
104
47
67
83
88
86
56
62
79
121
89
50
52
84
103
105
66
68
74
104
98
55
74
66
89
93
46
76
73
98
116
49
60
75
112
103
66
69
64
75
96
56
68
67
120
118
54
62
74
85
100
53
66
80
92
111
62
62
61
92
118
50
68
75
87
100
45
60
79
108
102
60
59
90
108
108
60
67
79
106
99
64
77
92
115
109
63
76
81
110
101
66
64
81
87
116
48
61
75
85
111
51
65
78
124
104
43
67
65
103
108
65
78
79
98
109
61
67
76
102
107
61
79
70
108
97
65
64
75
109
97
59
63
79
88
107
53
81
69
105
117
58
72
84
94
98
50
58
69
106
103
47
65
84
115
120
61
48
73
100
117
65
80
75
98
106
61
66
78
117
97
56
56
65
110
112
67
79
85
100
102
39
65
95
103
90
52
56
78
113
104
67
58
69
124
97
57
57
83
106
112
56
53
86
102
119
58
76
85
108
101
71
77
76
93
93
56
65
93
109
110
62
55
78
85
110
63
65
83
107
109
52
66
58
119
114
61
80
64
113
107
54
69
82
82
110
48
67
73
111
92
55
55
67
111
98
51
68
78
111
94
62
84
77
93
89
47
74
78
101
114
57
68
79
107
109
64
82
74
100
106
61
68
81
108
98
51
70
85
108
122
49
69
72
102
119
57
59
96
119
122
58
81
82
106
102
76
76
79
105
120
68
73
73
102
117
65
78
78
119
111
59
71
85
93
103
55
68
73
101
133
50
81
74
103
107
68
75
77
111
115
63
67
76
107
118
62
83
86
106
127
67
76
67
97
110
53
69
83
128
112
54
69
75
122
118
53
78
81
103
110
59
91
78
105
115
62
65
84
99
118
67
61
84
125
99
70
55
78
115
100
62
56
69
97
98
69
76
74
105
102
65
65
73
98
105
61
63
92
99
104
59
82
73
109
104
69
64
80
97
92
57
65
88
97
116
58
62
68
123
97
61
71
81
81
94
55
60
63
105
97
71
56
81
88
83
47
75
82
98
126
58
75
65
94
109
51
59
97
119
113
62
67
89
110
108
56
70
86
100
98
65
79
81
104
98
51
66
87
123
100
55
56
77
106
117
63
52
81
96
107
47
82
65
102
110
66
67
80
107
101
56
73
81
103
110
58
81
74
75
104
51
67
98
89
97
50
70
70
103
120
54
64
78
100
108
67
64
74
105
113
65
64
85
101
126
45
80
70
96
122
51
78
80
114
108
54
74
86
98
140
71
68
82
100
143
44
59
81
119
125
76
61
77
104
120
48
63
78
119
134
63
67
88
100
127
57
72
67
145
128
68
76
91
115
116
53
80
84
116
128
47
75
83
131
111
57
80
103
102
116
67
86
73
108
110
60
70
92
136
123
57
82
99
109
106
72
81
98
100
128
92
84
96
107
121
75
69
87
98
114
60
81
92
103
94
67
86
98
94
98
77
64
102
95
103
64
80
97
100
95
66
82
77
97
93
76
68
81
118
111
80
88
73
100
101
59
82
75
112
86
56
57
67
84
101
54
81
87
94
84
81
67
86
69
105
64
75
104
92
97
75
64
70
81
97
65
64
77
87
106
63
82
82
85
104
63
78
70
86
89
60
73
65
83
105
47
66
79
96
94
56
73
66
95
81
63
59
84
80
106
58
57
68
80
83
53
59
66
86
81
56
47
75
101
92
48
66
63
86
98
49
65
58
100
78
51
50
72
93
89
59
62
65
74
106
44
56
81
78
88
47
51
71
95
82
46
62
63
95
93
46
55
82
88
93
58
48
65
90
85
58
60
72
88
94
39
66
55
87
91
54
60
69
66
92
45
63
61
82
100
57
67
79
101
89
46
57
61
91
86
39
47
59
71
81
47
60
57
82
83
44
45
47
99
98
60
51
68
92
93
54
62
72
103
87
52
57
73
86
101
59
55
67
92
86
55
71
68
62
94
38
49
65
89
93
55
59
75
85
77
46
52
60
95
95
64
55
61
88
98
55
62
75
100
79
49
51
55
85
97
49
54
63
95
99
51
58
61
87
87
41
57
75
69
79
54
45
85
84
94
42
66
69
91
91
62
55
71
97
100
50
59
60
91
84
51
58
72
96
72
40
59
70
78
94
48
48
63
69
97
42
50
68
91
85
48
60
68
80
93
40
48
79
91
97
46
49
63
94
107
46
51
75
90
97
51
63
68
86
87
47
43
76
94
103
47
62
63
74
95
50
45
69
93
97
48
57
60
89
111
45
55
70
80
84
50
67
67
99
96
62
69
80
76
91
52
57
68
96
109
45
48
66
82
116
46
56
67
93
108
34
47
81
90
92
58
43
77
83
107
54
49
68
90
73
49
58
76
96
102
56
59
69
89
113
39
74
84
90
109
47
58
58
102
90
48
83
54
99
78
61
72
65
94
103
51
60
67
92
91
42
68
67
77
102
52
54
64
92
90
60
63
71
95
106
60
73
71
98
98
40
71
72
92
96
52
53
59
90
90
59
61
65
78
74
48
56
46
93
91
63
73
60
103
73
57
68
62
95
95
46
65
53
87
82
62
69
84
94
89
61
67
74
75
92
63
46
55
91
84
43
42
72
67
85
58
54
72
83
97
44
55
71
88
94
51
57
62
83
78
39
55
61
79
101
47
49
63
60
78
51
58
68
96
84
41
54
58
82
75
54
52
70
99
94
54
48
56
83
80
54
58
70
64
90
51
55
88
76
83
47
76
60
68
89
56
47
66
80
95
46
70
61
104
106
42
54
73
95
93
50
57
65
90
86
39
42
76
114
108
41
58
71
91
144
46
50
70
96
155
37
68
59
121
177
42
65
77
125
156
47
41
73
136
116
44
52
85
112
105
56
61
84
159
103
48
61
77
152
101
46
65
108
123
88
58
55
113
96
93
50
67
111
78
81
48
76
95
81
89
47
99
83
76
80
57
96
78
77
90
45
80
71
80
98
77
97
71
72
97
63
85
58
76
89
78
61
95
78
80
93
53
58
87
92
78
48
62
86
84
78
58
64
75
84
52
51
60
83
101
43
49
63
86
96
47
52
64
106
93
49
64
49
75
94
42
61
51
84
68
49
59
74
82
90
42
40
66
87
88
54
47
63
78
74
40
56
63
88
81
48
60
61
81
85
42
50
62
71
78
40
61
56
86
83
39
52
71
72
86
39
57
51
76
91
49
41
70
62
75
47
51
54
64
79
64
47
59
74
88
46
51
49
71
81
53
60
52
60
69
38
47
52
76
70
37
46
56
87
91
51
48
59
74
65
33
55
59
79
99
48
60
59
87
74
35
49
46
75
75
45
42
59
81
83
36
57
72
82
85
40
54
64
82
72
40
55
85
98
87
41
44
62
70
81
44
55
59
90
94
50
48
57
81
75
55
49
64
72
73
53
48
65
65
81
42
45
67
74
86
42
59
47
73
77
44
64
64
90
82
40
48
54
77
87
50
45
59
82
91
39
43
68
60
69
50
64
56
83
83
38
54
65
83
82
42
47
62
72
89
39
53
63
67
76
44
46
68
79
71
54
42
69
85
81
44
49
52
79
65
42
46
81
83
88
50
47
56
95
101
50
47
67
89
102
43
60
59
61
60
39
46
54
83
83
37
45
72
73
87
44
56
67
75
67
33
42
68
80
82
43
53
69
81
93
62
56
58
75
86
53
53
54
78
69
35
43
45
91
82
50
52
60
76
91
48
59
61
80
80
40
59
60
73
90
50
55
56
87
94
43
55
67
95
85
46
44
60
73
79
44
58
62
75
75
47
54
53
76
80
45
42
53
89
84
41
55
75
86
98
59
57
47
61
82
50
64
57
91
87
42
59
58
88
80
47
49
53
73
87
40
53
78
92
83
66
55
57
76
72
44
58
71
96
89
48
54
65
73
89
55
51
65
68
80
36
40
54
81
75
42
44
71
61
80
43
55
67
78
87
39
54
73
83
91
52
41
61
90
102
51
46
78
84
107
49
49
66
82
67
46
58
69
79
88
45
44
62
67
81
55
41
69
84
83
43
65
64
77
71
42
45
65
69
76
44
59
61
79
86
43
62
65
63
100
42
54
61
82
87
35
58
65
77
100
43
48
44
82
67
51
54
63
92
89
53
40
57
79
71
49
41
62
83
77
44
53
53
66
97
46
56
52
73
87
33
58
76
79
87
44
57
66
80
84
48
55
60
89
79
49
56
53
71
76
45
64
54
79
75
47
55
59
82
84
53
58
60
84
80
57
60
59
86
74
42
53
56
63
93
56
64
66
68
76
49
64
58
74
98
45
61
63
71
91
54
50
68
79
72
43
62
62
77
97
47
53
53
86
82
49
49
51
93
71
62
66
73
89
76
34
66
61
87
87
53
50
82
77
93
62
69
72
79
82
49
58
76
73
69
50
59
58
97
81
51
55
56
91
86
45
62
56
79
99
40
45
57
81
91
41
64
62
81
93
51
56
52
76
93
34
73
67
82
85
37
45
79
75
82
40
52
49
89
91
40
67
53
109
90
41
54
52
78
95
42
58
72
83
76
44
56
66
92
92
52
52
62
81
93
46
40
61
79
82
48
58
62
80
93
47
57
73
79
92
52
43
63
83
90
35
48
72
98
78
43
43
69
80
90
46
56
59
72
71
44
51
57
96
86
37
42
47
73
71
52
60
71
76
76
46
51
65
76
95
48
57
62
83
93
45
52
50
91
84
42
52
57
86
95
34
59
62
97
96
43
45
68
89
78
39
56
71
75
89
59
58
66
84
88
51
59
69
74
74
47
58
65
77
99
46
56
50
73
107
48
59
51
81
89
42
67
61
92
106
51
53
62
87
100
40
55
56
84
95
41
48
62
74
90
48
53
62
77
99
41
48
62
86
80
57
60
66
70
72
33
54
65
103
78
50
52
80
79
83
46
52
62
80
96
51
56
55
83
71
36
54
74
89
92
52
56
58
83
90
50
48
59
90
94
44
60
61
86
81
42
42
62
92
105
48
58
73
91
91
40
54
59
93
75
58
65
68
95
88
49
48
75
87
85
40
53
90
87
81
43
57
62
94
88
51
56
76
90
79
32
50
83
81
109
50
56
68
84
93
46
52
64
76
77
51
65
43
86
72
53
63
55
70
85
57
53
64
92
82
55
43
78
94
94
55
53
71
87
86
44
52
71
86
93
49
63
59
73
84
43
53
58
81
99
51
59
53
80
90
45
52
63
91
93
46
63
62
79
90
39
52
72
88
83
53
50
54
92
83
43
59
62
90
94
52
62
70
93
101
50
65
84
92
95
46
68
51
93
75
41
51
64
80
101
50
42
52
91
84
48
42
61
86
98
43
57
74
86
89
47
47
67
84
84
38
57
73
83
86
61
57
62
66
72
41
42
76
90
93
42
55
53
83
86
49
43
80
77
88
49
61
86
94
83
54
63
59
86
107
44
51
60
84
100
43
63
68
74
99
57
55
69
93
99
46
60
84
94
96
56
64
70
82
91
28
59
57
94
105
48
49
75
70
89
49
62
74
70
79
45
52
66
95
98
57
72
66
92
94
58
62
70
86
96
50
50
66
84
76
54
46
59
89
94
50
59
68
77
98
56
44
62
73
106
43
69
62
80
86
51
60
75
86
90
57
67
65
78
93
37
53
62
89
88
49
55
63
90
80
54
60
43
88
70
48
54
76
85
99
44
62
64
101
92
52
66
58
79
84
50
62
71
86
77
49
63
70
90
95
45
60
70
85
116
55
61
60
87
81
52
62
72
85
87
60
64
74
84
89
47
65
66
98
100
45
61
63
88
102
53
63
61
93
98
42
67
73
93
104
45
57
67
88
118
47
52
72
72
96
48
55
83
92
98
45
71
67
83
109
59
53
58
100
94
33
46
69
97
96
46
57
76
104
86
43
60
69
76
91
63
57
69
76
105
55
69
92
77
111
46
67
85
64
101
65
67
72
83
105
46
68
58
73
97
48
54
61
90
96
41
52
77
93
86
50
66
85
81
88
56
54
86
88
107
60
62
80
89
95
57
52
66
68
108
46
62
68
76
85
60
67
71
113
87
41
67
59
89
84
39
63
72
87
83
48
61
71
87
111
57
62
81
93
95
36
59
75
102
92
49
45
56
101
88
47
65
61
92
92
43
54
66
86
81
55
47
67
69
99
43
61
69
85
84
56
55
75
98
99
38
56
79
76
107
54
47
70
83
84
40
45
67
83
93
56
52
70
98
83
49
51
72
71
115
52
63
64
83
95
57
45
73
87
88
48
61
65
78
100
45
53
63
76
90
34
55
80
92
84
41
54
69
69
87
56
51
59
113
98
37
57
66
86
98
52
68
63
99
93
38
68
82
104
99
47
55
72
89
101
46
51
66
110
99
55
55
60
81
111
54
58
54
84
111
51
63
88
106
92
45
56
71
100
106
51
63
68
72
93
51
62
79
81
82
46
51
58
73
89
50
57
75
80
83
44
67
67
105
108
42
55
66
75
102
46
62
47
119
98
58
60
66
97
93
45
56
86
98
96
50
61
68
86
102
51
47
59
94
102
50
56
76
109
93
49
62
62
82
88
46
62
82
97
98
55
62
70
87
99
49
53
49
89
79
55
44
72
88
103
50
67
68
109
84
48
52
78
109
105
54
55
65
72
86
38
61
72
82
96
47
65
75
106
94
53
57
69
74
99
50
58
66
89
96
50
45
80
103
101
51
57
66
87
89
54
57
72
90
89
44
64
63
94
94
43
50
67
83
93
61
55
64
111
72
36
68
80
89
104
57
62
77
78
106
57
66
62
98
121
48
73
78
88
110
53
65
77
93
96
55
65
72
83
98
38
75
65
100
99
46
69
72
89
114
41
61
75
105
93
39
61
68
110
78
55
68
66
87
92
58
61
80
97
94
45
74
80
89
106
47
62
83
102
92
59
63
60
96
79
44
66
75
99
80
49
54
79
107
100
57
56
86
80
112
54
60
62
99
117
48
49
70
82
103
56
68
80
92
90
66
73
70
92
99
48
60
62
109
91
49
51
72
106
81
49
59
84
97
84
55
62
73
89
95
50
51
67
111
98
52
58
78
104
96
52
65
80
93
93
53
59
72
89
87
53
52
65
102
78
54
63
70
86
90
50
51
67
86
85
51
67
67
86
98
60
60
73
76
96
35
63
72
73
100
57
56
79
112
100
47
75
82
83
113
58
72
71
96
105
64
62
76
97
90
58
53
69
105
94
51
55
62
83
104
49
59
92
86
99
51
62
76
93
94
55
64
110
102
92
45
60
65
95
87
54
53
82
96
94
60
78
75
84
122
41
59
56
101
97
53
63
73
104
96
66
55
87
113
97
49
50
67
94
107
48
57
55
79
134
62
71
74
88
88
45
59
70
78
107
53
53
68
95
110
46
65
84
86
72
62
55
70
94
109
59
68
60
90
109
44
65
69
111
89
46
69
59
90
102
49
65
71
103
108
44
60
87
83
101
52
64
69
90
89
58
60
84
93
111
52
56
87
93
97
61
61
73
90
98
49
57
63
107
96
52
72
82
100
99
69
57
75
78
93
52
51
73
84
104
55
64
82
96
84
51
51
72
98
88
62
63
81
89
105
47
47
71
81
97
65
49
65
93
126
44
52
80
108
87
49
55
63
77
88
59
65
65
109
108
52
74
66
112
102
47
57
82
96
80
58
69
60
99
95
45
70
69
89
96
46
76
75
124
90
44
58
65
95
93
60
68
80
102
85
52
65
72
109
111
48
61
76
115
107
49
60
73
110
95
61
67
74
103
107
58
64
83
100
109
43
61
63
93
97
62
77
59
91
93
47
68
61
101
128
48
55
76
92
97
68
53
82
103
87
52
59
64
84
96
64
62
81
96
93
54
81
55
99
111
59
88
77
100
103
48
52
76
101
135
52
61
79
103
113
63
51
76
90
115
60
72
94
82
104
55
71
76
91
112
51
59
46
100
100
59
75
92
95
95
59
70
81
106
110
39
60
70
86
102
55
73
91
110
134
60
64
89
105
116
61
76
85
101
105
56
87
66
92
97
61
61
70
89
125
58
76
69
99
99
52
75
84
65
90
62
65
84
96
106
55
72
67
89
102
55
65
66
89
79
36
69
70
95
96
61
70
68
82
85
71
54
65
70
92
61
62
68
91
76
51
59
59
64
73
58
65
65
76
58
60
64
50
72
78